[package]
name = "GizeDao"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
#W3libs = { git = "https://github.com/seapad-fund/w3libs", rev = "devnet" }

[addresses]
gize="0x0"
sui="0x2"

dao_admin="0x9d6f2e34e937842df89642cd96fba8509d4e47d297f716ce3a44df3070a79851"